DATASET:
  root: ./data/geospatial
  name: OSCD
  train_transforms:
    normalize: true
    standardize: false
  eval_transforms:
    normalize: true
    standardize: false
  kwargs:
    bands: all
    patch_size: 96
  eval_metric: f1 
  task_type: change_detection
  use_train_transform: true
  train_frac: 1.0 
  val_frac: 0.1
  train_split: train
  task_head_kwargs:
    head_type: unet 
    num_classes: 1 
    patch_size: 96
    feature_indices: [0, 4, 6, 8, 10, 12]
    feature_channels: [1, 2, 8, 32, 128, 512]
  # task_head_kwargs:
  #   head_type: linear
  #   num_classes: 96*96