DATASET:
  root: ./data/geospatial
  name: SSL4EO
  train_transforms:
    normalize: true
    standardize: false
  kwargs:
    optical_split: s2c
    radar_split: s1
  eval_metric: classification
  task_type: pretrain
  use_train_transform: true
  train_frac: 1
  train_split: train