MODEL:
  architecture: vit_base_patch16_224
  cross_modal: true
  unified_decoder: true
  mask_ratio: 0.75
  channel_mask_ratio: 0.75
  use_clip: false
  use_siglip: false
  OPTICAL:
    channel_vit: true
    kwargs:
      img_size: 224
      patch_size: 16
      in_chans: 13
      embed_dim: 768
      depth: 12
      num_heads: 12
      mlp_ratio: 4.0
      qkv_bias: True
      drop_path_rate: 0.0
      drop_path_uniform: False
      init_values: null
      num_register_tokens: 0
      channel_pool: max
      spectral_blocks: 0
      sptial_spectral_blocks: 0
  RADAR:
    channel_vit: false
    kwargs:
      img_size: 224
      patch_size: 16
      in_chans: 2
      embed_dim: 768
      depth: 12
      num_heads: 12
      mlp_ratio: 4.0
      qkv_bias: True
      drop_path_rate: 0.0
      drop_path_uniform: False
      init_values: null
      num_register_tokens: 0
  DECODER:
    kwargs:
      out_chans: 15
      num_heads: 16
      mlp_ratio: 4.0
      qkv_bias: True
      init_values: null
      decoder_embed_dim: 512 
      decoder_depth: 8
      decoder_num_heads: 16
      num_patches: 196
      patch_size: 16
      num_register_tokens: 0
      embed_dim: 768