MODEL:
  architecture: vit_base_patch16_224
  handle_modal: multi_modal
  mask_ratio: 0.75
  channel_mask_ratio: 0.5
  MULTI_MODAL:
    custom_vit: multi_modal_channel_vit
    freeze_encoder: false
    use_head: false
    kwargs:
      img_size: 224
      patch_size: 16
      optical_in_chans: 13
      radar_in_chans: 2
      embed_dim: 768
      depth: 12
      num_heads: 12
      mlp_ratio: 4.0
      qkv_bias: True
      drop_path_rate: 0.0
      drop_path_uniform: False
      init_values: null
      num_register_tokens: 0
      channel_pool: max
      spectral_blocks: 0
      sptial_spectral_blocks: 12
  DECODER:
    kwargs:
      optical_out_chans: 13
      radar_out_chans: 2
      num_heads: 16
      mlp_ratio: 4.0
      qkv_bias: True
      init_values: null
      decoder_embed_dim: 512 
      decoder_depth: 8
      decoder_num_heads: 16
      num_patches: 196
      patch_size: 16
      num_register_tokens: 0
      embed_dim: 768