DATASET:
  root: ./data/geospatial
  name: So2Sat
  kwargs:
    version: 3_culture_10
    bands: ['S2_B02', 'S2_B03', 'S2_B04', 'S2_B05', 'S2_B06', 'S2_B07', 'S2_B08', 'S2_B8A', 'S2_B11', 'S2_B12']
    pad_s2: true
  eval_metric: classification
  use_train_transform: true
  train_frac: 0.1
  train_transforms:
    standardize: false
  eval_transforms:
    standardize: false
MODEL:
  architecture: resnet50
  bands: 13
  load_pretrained_from: torchgeo
  pretrained_ckpt: ResNet50_Weights.SENTINEL2_ALL_MOCO
  criterion: cross_entropy
  freeze_encoder: false
  head_kwargs:
    head_type: linear
    task_type: classification
    use_bias: true
    in_features: 2048
    num_classes: 17
TRAINER:
  # Training related
  num_train_epochs: 100
  per_device_train_batch_size: 512
  per_device_eval_batch_size: 512
  gradient_accumulation_steps: 1
  learning_rate: 1e-5
  weight_decay: 0.
  # dataloader
  dataloader_num_workers: 8
  dataloader_pin_memory: true
  dataloader_drop_last: false
  # Logging
  report_to: wandb
  # optimizer
  optim: adamw_torch
  lr_scheduler_type: cosine
  # Other
  seed: 0

