MODEL:
  architecture: resnet50
  bands: 13
  load_pretrained_from: torchgeo
  pretrained_ckpt: ResNet50_Weights.SENTINEL2_ALL_MOCO
  criterion: cross_entropy
  freeze_encoder: false
  head_kwargs:
    head_type: linear
    task_type: classification
    use_bias: true
    in_features: 2048
    num_classes: 19
SAR_MODEL:
  architecture: resnet50
  bands: 2
  load_pretrained_from: dir
  pretrained_ckpt: /data/common/huggingface_models/SSL4EO/B2_rn50_moco.pth
  criterion: cross_entropy
  freeze_encoder: false
  head_kwargs:
    head_type: linear
    task_type: classification
    use_bias: true
    in_features: 2048
    num_classes: 19
DATASET:
  root: ./data/geospatial
  name: BigEarthNet
  train_transforms:
    normalize: true
    standardize: false
  eval_transforms:
    normalize: true
    standardize: false
  kwargs:
    bands: all
    num_classes: 19
    pad_s2: true
  eval_metric: classification
  use_train_transform: false
  train_frac: 0.1
TRAINER:
  # Training related
  num_train_epochs: 50
  per_device_train_batch_size: 256
  per_device_eval_batch_size: 256
  gradient_accumulation_steps: 1
  learning_rate: 1e-4
  weight_decay: 0.
  # dataloader
  dataloader_num_workers: 8
  dataloader_pin_memory: true
  dataloader_drop_last: false
  # Logging
  report_to: wandb
  logging_steps: 50
  # optimizer
  optim: adamw_torch
  lr_scheduler_type: cosine
  # Other
  seed: 0