TRAINER:
  # Training related
  num_train_epochs: 100
  per_device_train_batch_size: 512
  per_device_eval_batch_size: 512
  gradient_accumulation_steps: 1
  learning_rate: 1e-4
  weight_decay: 0.01
  # dataloader
  dataloader_num_workers: 8
  dataloader_pin_memory: true
  dataloader_drop_last: false
  # optimizer
  optim: adamw_torch
  lr_scheduler_type: cosine
  warmup_epochs: 1
  scheduler_kwargs: null
  # Model saving & evaluation
  save_strategy: epoch
  evaluation_strategy: epoch
  load_best_model_at_end: true
  metric_for_best_model: accuracy
  greater_is_better: true
  # Logging
  logging_dir: "./results/logs"
  logging_strategy: steps
  logging_steps: 10
  report_to: wandb
  # Checkpoints & Output
  output_dir: "./results/models"
  save_total_limit: 5
  overwrite_output_dir: false
  # Other
  seed: 0
  fp16: true
  push_to_hub: false
TRAINER_EXTRA:
  early_stop:
    enable: false
    patience: 5
    threshold: 0.0
LOGGER:
  project: "GeoFoundation"
  entity: "ehzoahis"
  dir: "./results/"
DATASET:
  root: ./data/geospatial
  name: ''
  kwargs:
    bands: all
  train_transforms:
    crop_size: 224
    hflip_prob: 0.5
    normalize: false
    standardize: true
  eval_transforms:
    crop_size: 224
    resize_size: 256
    normalize: false
    standardize: true
  eval_metric: ''
  use_train_transform: true
  train_frac: 1.0
  val_frac: 1.0
  train_split: trainval
MODEL:
  architecture: null
  cross_modal: false
  unified_decoder: false
  mask_ratio: 0.
  channel_mask_ratio: 0.
  freeze_encoder: false
  use_siglip: false
  load_pretrained_from: null
  pretrained_ckpt: null
  OPTICAL:
    freeze_encoder: false
    channel_vit: false
    kwargs:
      img_size: 224
      patch_size: 16
      in_chans: 13
      embed_dim: 384
      depth: 12
      num_heads: 6
      mlp_ratio: 4.0
      qkv_bias: True
      drop_path_rate: 0.0
      drop_path_uniform: False
      init_values: null
      num_register_tokens: 0
    use_head: false
    head_kwargs:
      use_bias: true
  RADAR:
    freeze_encoder: false
    channel_vit: false
    kwargs:
      img_size: 224
      patch_size: 16
      in_chans: 2
      embed_dim: 384
      depth: 12
      num_heads: 6
      mlp_ratio: 4.0
      qkv_bias: True
      drop_path_rate: 0.0
      drop_path_uniform: False
      init_values: null
      num_register_tokens: 0
    use_head: false
    head_kwargs:
      use_bias: true
  DECODER:
    kwargs:
      out_chans: 15
      num_heads: 12
      mlp_ratio: 4.0
      qkv_bias: True
      init_values: null
      decoder_embed_dim: 512 
      decoder_depth: 8 
      decoder_num_heads: 16
      num_patches: 196
      patch_size: 16
      num_register_tokens: 0
      embed_dim: 384