DATASET:
  root: ./data/geospatial
  name: EuroSAT
  kwargs:
    bands: [B01, B02, B03, B04, B05, B06, B07, B08, B08A, B09, B10, B11, B12]
  eval_metric: classification
MODEL:
  name: vit_small_patch16_224
  load_encoder: ViTSmall16_Weights.SENTINEL2_ALL_DINO
  in_features: 384
  out_features: 10
  lp: True
TRAINER:
  # Training related
  num_train_epochs: 100
  per_device_train_batch_size: 512
  per_device_eval_batch_size: 512
  gradient_accumulation_steps: 1
  learning_rate: 1e-2
  weight_decay: 0.01
  # dataloader
  dataloader_num_workers: 8
  dataloader_pin_memory: true
  dataloader_drop_last: false
  # optimizer
  optim: adamw_torch
  lr_scheduler_type: reduce_lr_on_plateau
  # Other
  seed: 0

  

