MODEL:
  architecture: mm_cvit_base_patch16_224
LOSS:
  Spectral:
    scale: 1.0
  MAE:
    scale: 1.0
  CrossModalLoss:
    scale: 1.0
    use_mask: false
DATASET:
  name: SSL4EO
  # root: ./data/geospatial
  # name: BigEarthNet
  # train_transforms:
  #   normalize: true
  #   standardize: false
  # eval_transforms:
  #   normalize: true
  #   standardize: false
  # kwargs:
  #   bands: all
  #   num_classes: 19
  #   pad_s2: true
  # eval_metric: classification
  # task_type: pretrain
  # use_train_transform: true
  # train_frac: 1
  # val_frac: 0.1
  # train_split: trainval
TRAINER:
  # Training related
  num_train_epochs: 20
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 64
  gradient_accumulation_steps: 1
  learning_rate: 1.5e-4
  weight_decay: 0.05
  # dataloader
  dataloader_num_workers: 8
  dataloader_pin_memory: true
  dataloader_drop_last: false
  # Logging
  report_to: wandb
  logging_steps: 50
  # optimizer
  optim: adamw_torch
  lr_scheduler_type: cosine
  warmup_epochs: 5
  # Other
  seed: 0
  # ckpt
  save_frequency: 10
